//───────────────────────────────────────────────────────────────
//   ApplyBulkReplacementsOneTextColumn
//   ----------------------
//   Params:
//     • Source        – the table to transform (a one of the steps in M code)
//     • ColumnName  – a chosen column (without the square brackets and within quotation
//     • Replacements  – a list whose items are to be replaced with what 
      
//         { OldValue , NewValue}
//   Returns:
//     A new table with every rule applied in sequence.
//
//    Example: fxApplyBulkReplacementsOneTextColumn(#"Step | Used Before", "Name of column without aquare brackets", {{"ValueX", "ValueY"}, {"ValueZ", "ValueY"}})
//───────────────────────────────────────────────────────────────
let
    ApplyBulkReplacementsOneTextColumn =
        ( Source       as table, 
          ColumnName as text,       // required
          Replacements as list        // required
        ) as table =>

        let
            // Single-rule helper (no recursion)
            ReplaceFn =
                (state as table, rule as list) as table =>
                    Table.ReplaceValue(
                        state,
                        rule{0},            // old value
                        rule{1},            // new value
                        Replacer.ReplaceText,            // Replacer (Text, Value, etc.)
                        { ColumnName  }         // column as a 1-item list
                    ),

            // Fold all rules onto the starting table
            Result = List.Accumulate(Replacements, Source, ReplaceFn)
        in
            Result
in
    ApplyBulkReplacementsOneTextColumn
